"""rename 'favorites_movies' -> 'favorite_movies'

Revision ID: 26f7d55d3650
Revises: 3085586f3357
Create Date: 2026-07-09 19:31:42.064538

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26f7d55d3650"
down_revision: Union[str, Sequence[str], None] = "3085586f3357"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("favorites_movies", "favorite_movies")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("favorite_movies", "favorites_movies")
    # ### end Alembic commands ###
