"""add refresh token class

Revision ID: 76d1485c8b69
Revises: b5e81e79157c
Create Date: 2026-07-12 09:40:24.723149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76d1485c8b69"
down_revision: Union[str, Sequence[str], None] = "b5e81e79157c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_refresh_token_hash"),
        "refresh_tokens",
        ["refresh_token_hash"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_auth_sessions_refresh_token_hash"), table_name="auth_sessions"
    )
    op.drop_column("auth_sessions", "refresh_token_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_sessions",
        sa.Column(
            "refresh_token_hash", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.create_index(
        op.f("ix_auth_sessions_refresh_token_hash"),
        "auth_sessions",
        ["refresh_token_hash"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_refresh_tokens_refresh_token_hash"), table_name="refresh_tokens"
    )
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
